BENCH_TAG="[BENCH]"

TYPE_ADD_CHUNK = "[ADD_CHUNK]"
TYPE_QUERY_CHUNK_ADDR = "[QUERY_CHUNK_ADDR]"
TYPE_QUERY_CHUNK_LOCAL= "[QUERY_CHUNK_LOCAL]"
TYPE_STORE_CHUNK_LOCAL = "[STORE_CHUNK]"
TYPE_STORE_CHUNK_REMOTE = "[CALL_STORE_CHUNK]"

ENTRY_TOTAL_STORE_LOCAL = "time_total_rpc_store"
ENTRY_TOTAL_LOCAL_QUERY = "time_total_local_query"
ENTRY_GET_AND_CHECK = "time_get_and_check_chunk"
ENTRY_CHECK_TOKEN_VALID = "time_check_token_valid"
ENTRY_TIME_FIND_VALUE = "time_find_value"
ENTRY_CRAWL_NEAREST = "time_crawl_nearest"
ENTRY_TOTAL_ADD_CHUNK = "time_total_add_chunk"
ENTRY_TOTAL_QUERY_CHUNK = "time_total_query_chunk"
ENTRY_FETCH_POLICY = "time_fetch_policy"
ENTRY_STORE_CHECK = "time_store_check_chunk"
ENTRY_STORE_TO_ALL_NODES = "time_store_to_nodes"
ENTRY_TIME_WELCOME_NODE = "time_welcome_node"
ENTRY_STORE_ONE_NODE = "time_call_store"